### ISSUE TITLE
MaterialAccount not supporting more than 3 accounts

### ISSUE THREAD

**Issue by YeikSoft** [neokree/MaterialNavigationDrawer#149]
Hi, when i use the MaterialAccount with 3 or less accounts it works fine. But when i add the fourth account, the header does not appear correctly.
![captura de pantalla 2015-01-30 a la s 8 33 53 a m](https://cloud.githubusercontent.com/assets/1945675/5976451/ee8826fa-a85b-11e4-868a-47966aa726d9.png)

![captura de pantalla 2015-01-30 a la s 8 38 49 a m](https://cloud.githubusercontent.com/assets/1945675/5976456/ff02ff78-a85b-11e4-9eaf-451708b76e85.png)

**Comment by neokree** [comment]
I have released now a bug fix on github

**Comment by melody-dev** [comment]
I use latest version(1.3), why i still face this problem when added more than 3 accounts ?

**Comment by neokree** [comment]
Because the last release have this bug, this issue have the "avariable in the next release" label, so You should wait for the next release, or you can use the dev project (MaterialNavigationDrawerModule folder on github).
