### ISSUE TITLE
Out of memory errors

### ISSUE THREAD

**Issue by yanivagman** [neokree/MaterialNavigationDrawer#60]
When running the app on my smartphone (galaxy S5), A crash happens because of an out of memory error. This error always happens at init function, when running the MaterialAccount constructor, at the stage of loading the navigation drawer background photo.
The crash happens while doing one of the following:
1. When rotating the phone to landscape mode.
2. When exiting the app with back button and starting the app again

 Using memory monitor in Android studio, memory usage goes up to 200Mb, then the crash happens.

I think the reason for the crash is allocating too much memory for the Bitmaps.
When rotating the phone, or exiting, then re-entring, it might be the garbage collector didn't dispose all the bitmaps that was allocated before (when previously running the MaterialAccount constructors), thus causing the crash when allocating again.

I think 2 steps might help here:
1. Dispose allocated memory with nulling the pointer in "onStop()"
2. Better manage bitmaps

The following docs can help here:
1. https://developer.android.com/training/articles/memory.html
which also mention to "Avoid wasting memory with bitmaps".
2. https://developer.android.com/training/displaying-bitmaps/manage-memory.html

**Comment by treylon** [comment]
I'm experiencing the exact same problem on my Nexus 5. My app crashes with the same error and I'm suspecting the same problem.

**Comment by mohd-bh** [comment]
I had the same issue. I would like to suggest using this library since it handles this issue:
https://github.com/hdodenhof/CircleImageView

**Comment by neokree** [comment]
thank you for your help @mohd-bh

**Comment by mohd-bh** [comment]
@neokree on what version you are planning to make a fix for this issue?

**Comment by neokree** [comment]
For the next release, but I need some help for testing purpose :smile:
I will commit in the next days a new dev module with a possible solution, any of you would try this fix before I will release a new version?

**Comment by mohd-bh** [comment]
@neokree let me know if you need a help in testing it, i can do that.

**Comment by neokree** [comment]
I committed the dev version now, I tried with some virtual and real devices and no outofmemory error appear. Let me know

**Comment by mohd-bh** [comment]
I just tried it, it takes now longer till it crashes, but it still not fixed..
here is the error log

try to watch the memory usage using "Memory monitor" in android studio
it shows that memory usage increases every time you open the drawer activity.

`````
01-05 22:45:26.701    7529-7529/itcs.mohd.socialy E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: itcs.mohd.socialy, PID: 7529
    java.lang.OutOfMemoryError
            at android.graphics.Bitmap.nativeCreate(Native Method)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:810)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:787)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:754)
            at it.neokree.materialnavigationdrawer.MaterialAccount.getCroppedBitmapDrawable(MaterialAccount.java:136)
            at it.neokree.materialnavigationdrawer.MaterialAccount.getCircularPhoto(MaterialAccount.java:105)
            at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer.notifyAccountDataChanged(MaterialNavigationDrawer.java:1005)
            at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer.onCreate(MaterialNavigationDrawer.java:426)
            at android.app.Activity.performCreate(Activity.java:5231)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
            at dalvik.system.NativeStart.main(Native Method)
````

**Comment by javmarina** [comment]
http://developer.android.com/training/displaying-bitmaps/index.html
Maybe manipulating bitmaps off the UI thread?

**Comment by neokree** [comment]
the main problem I think is that the init() method, with all the new account (that contains the resources), causes the overload of the RAM. 
The problem is that every sections and accounts not persists when device rotate/ another activity is called and then the user go back to the navigation drawer. So every time the init() is called, the activity loads on RAM bitmaps and drawable. Maybe I can cache bitmaps and reload it only when necessary.
Another type of work is declare the list of sections and accounts static, so they should persist to the activity lifecycle

**Comment by mkosik** [comment]
recycling bitmaps might help or you might use static variables that will persist, not re-create them everytime.
btw, is a background image already resized to (in most cases) a smaller bitmap needed at given res or just fitted in a View? Because there might be some hi-res photos user e.g. set online as their profile BGs that might eat MBs of RAM (till resolved, cumulated everytime init() is called).

**Comment by mohd-bh** [comment]
I noticed in MaterialAccount.java it creates a Bitmap everytime the activity is re-opened.

I suggest you to re-use the created bitmap instead of creating a new one,

declare it as a static and check if it's null, then create it if not re-use

```
Bitmap bitmap = convertToBitmap(drawable);
        Bitmap output = Bitmap.createBitmap(bitmap.getWidth(),
                bitmap.getHeight(), Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(output);
```

**Comment by neokree** [comment]
@mohd-bh at this time every time the activity is reopened  the list of accounts is re-initiated and the init() method is called for populate it. So every time developers call the newAccount() method a new MaterialAccount is instantiated. 
declare static the bitmap can't solve this problem because they will be null at every call.

**Comment by neokree** [comment]
I have committed a new version, now the bitmaps are resized and converted into drawable into an asyctask.

If it is not enought, I will cache the bitmaps into the memory, but there is a little problem with that approach, because I need to find a method for retriving the correct bitmap into memory, so I don't know how to do the naming for each bitmap.

**Comment by mohd-bh** [comment]
@neokree  what does the "res" represents in the constructor of MaterialAccount?

**Comment by neokree** [comment]
"resources"

**Comment by mohd-bh** [comment]
@neokree  I just tested it, no crashing at all

**Comment by neokree** [comment]
Well, thank you @mohd-bh for have tested the code, and thanks to all for the helps!
